[package]
name    = "anyrun-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard       = { features = [ "wayland-data-control" ], version = "3.4" }
chrono        = "0.4.42"
fuzzy-matcher = "0.3.7"
serde         = { features = [ "derive" ], version = "1.0" }
